# Generated by generate_tests (from the Hokohoko project).
import unittest as ut


class TestData(ut.TestCase):
    def test_init_sets_internal_values_correctly(self):
        """Auto-generated from _Data.py:44"""
        self.fail('TODO: Implement me!')


if __name__ == '__main__':
    ut.main()
