# Generated by generate_tests (from the Hokohoko project).
import unittest as ut


class TestPredictor(ut.TestCase):
    def test_init_initialises_the_internal_random_reliably(self):
        """Auto-generated from _Predictor.py:43"""
        self.fail('TODO: Implement me!')

    def test_init_sets_internal_values_correctly(self):
        """Auto-generated from _Predictor.py:43"""
        self.fail('TODO: Implement me!')

    def test_place_order_places_order_into_orders(self):
        """Auto-generated from _Predictor.py:177"""
        self.fail('TODO: Implement me!')

    def test_place_orders_places_all_orders_into_orders(self):
        """Auto-generated from _Predictor.py:189"""
        self.fail('TODO: Implement me!')


if __name__ == '__main__':
    ut.main()
