# Generated by generate_tests (from the Hokohoko project).
import unittest as ut


class TestNpz(ut.TestCase):
    def test_enter_raises_an_error_if_parameters_has_no_filename(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_file_doesnt_exist(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_start_override_is_negative(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_end_override_is_less_than_start_override(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_symbol_subset_is_not_a_string(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_origin_is_negative(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_end_is_less_than_origin(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_raises_an_error_if_lock_is_not_a_lock(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_loads_all_the_symbols_correctly(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_loads_only_the_specified_symbols(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_loads_the_requested_timestamps_only(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_loads_the_requested_data_only(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_enter_doesnt_load_data_if_load_is_false(self):
        """Auto-generated from _Npz.py:107"""
        self.fail('TODO: Implement me!')

    def test_get_symbol_ids_returns_the_correct_symbol_ids(self):
        """Auto-generated from _Npz.py:180"""
        self.fail('TODO: Implement me!')

    def test_get_minutes_returns_the_correct_count_of_minutes(self):
        """Auto-generated from _Npz.py:194"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_raises_an_error_if_origin_is_negative(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_raises_an_error_if_end_is_less_than_origin(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_returns_two_arrays(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_first_array_returned_is_timestamps(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_second_array_returned_is_exchange_rate_data(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_returns_expected_data_for_all_symbols(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')

    def test_get_partial_data_returns_expected_data_for_specified_symbols(self):
        """Auto-generated from _Npz.py:206"""
        self.fail('TODO: Implement me!')


if __name__ == '__main__':
    ut.main()
