# Generated by generate_tests (from the Hokohoko project).
import unittest as ut


class TestHokohoko(ut.TestCase):
    def test__make_config_from_arguments_returns_a_HokohokoConfig(self):
        """Auto-generated from Hokohoko.py:83"""
        self.fail('TODO: Implement me!')

    def test__make_config_from_arguments_defaults_are_set_correctly(self):
        """Auto-generated from Hokohoko.py:83"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_returns_the_correct_number_of_periods(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_if_possible_the_periods_are_the_correct_length(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_training_testing_and_hold_periods_are_correct(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_raises_an_error_if_the_settings_dont_work_on_the_given_data_source(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_returns_an_iterable_of_PeriodConfigs(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_all_PeriodConfigs_are_unique(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_doesnt_oversaturate(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_periods_include_the_available_symbols(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__calculate_periods_respects_load_limit_if_possible(self):
        """Auto-generated from Hokohoko.py:186"""
        self.fail('TODO: Implement me!')

    def test__process_returns_an_account(self):
        """Auto-generated from Hokohoko.py:247"""
        self.fail('TODO: Implement me!')

    def test__process_generates_profiles_if_configured(self):
        """Auto-generated from Hokohoko.py:247"""
        self.fail('TODO: Implement me!')

    def test_run_a_known_benchmark_with_debug_produces_an_account_with_known_results(self):
        """Auto-generated from Hokohoko.py:278"""
        self.fail('TODO: Implement me!')

    def test_run_a_known_simulation_with_debug_produces_an_account_with_known_results(self):
        """Auto-generated from Hokohoko.py:278"""
        self.fail('TODO: Implement me!')


if __name__ == '__main__':
    ut.main()
