# Generated by generate_tests (from the Hokohoko project).
import unittest as ut


class TestUtils(ut.TestCase):
    def test_get_fq_class_raises_an_error_it_it_cant_access_the_module(self):
        """Auto-generated from utils.py:49"""
        self.fail('TODO: Implement me!')

    def test_get_fq_class_raises_an_error_if_it_cant_access_the_class(self):
        """Auto-generated from utils.py:49"""
        self.fail('TODO: Implement me!')

    def test_get_fq_class_accepts_singlehierarchy_class(self):
        """Auto-generated from utils.py:49"""
        self.fail('TODO: Implement me!')

    def test_get_fq_class_accepts_fully_qualified_class(self):
        """Auto-generated from utils.py:49"""
        self.fail('TODO: Implement me!')

    def test_get_fq_class_returns_the_correct_class(self):
        """Auto-generated from utils.py:49"""
        self.fail('TODO: Implement me!')

    def test_convert_symbol_to_id_raises_an_error_on_empty_symbol(self):
        """Auto-generated from utils.py:77"""
        self.fail('TODO: Implement me!')

    def test_convert_symbol_to_id_raises_an_error_if_symbol_is_not_string(self):
        """Auto-generated from utils.py:77"""
        self.fail('TODO: Implement me!')

    def test_convert_symbol_to_id_returns_a_numpyint64(self):
        """Auto-generated from utils.py:77"""
        self.fail('TODO: Implement me!')

    def test_convert_symbol_to_id_returns_the_correct_value(self):
        """Auto-generated from utils.py:77"""
        self.fail('TODO: Implement me!')

    def test_convert_id_to_symbol_raises_an_error_if_not_provided_a_number(self):
        """Auto-generated from utils.py:99"""
        self.fail('TODO: Implement me!')

    def test_convert_id_to_symbol_returns_a_string(self):
        """Auto-generated from utils.py:99"""
        self.fail('TODO: Implement me!')

    def test_convert_id_to_symbol_returns_the_correct_string(self):
        """Auto-generated from utils.py:99"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_raises_an_error_if_not_provided_an_array(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_returns_a_dictionary_of_tuples(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_all_symbols_are_mapped_to_their_own_index(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_symbols_that_are_base_currency_already_map_to_themselves(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_symbols_map_to_the_correct_base_pair(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_symbols_map_to_the_correct_reversed_base_pair(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_symbols_that_dont_have_a_base_connection_map_to_None(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')

    def test_generate_currency_map_the_base_currency_gets_changed_correctly(self):
        """Auto-generated from utils.py:117"""
        self.fail('TODO: Implement me!')


if __name__ == '__main__':
    ut.main()
